In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

from xgboost import XGBClassifier

import joblib

In [2]:
df = pd.read_csv("Disease_and_Symptoms_Preprocessed.csv")

In [3]:
df.head()

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
0,panic disorder,1,0,1,1,0,0,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,panic disorder,0,0,1,1,0,1,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,panic disorder,1,1,1,1,0,1,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,panic disorder,1,0,0,1,0,1,1,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,panic disorder,1,1,0,0,0,0,1,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
df.shape

(50238, 378)

In [5]:
df.isnull().sum().sum()

np.int64(268)

In [6]:
missing = df.isnull().sum()
missing = missing[missing > 0]
print(missing)

ear pain                        1
jaw swelling                    1
mouth dryness                   1
neck swelling                   1
knee pain                       1
                               ..
hip weakness                    1
back swelling                   1
ankle stiffness or tightness    1
ankle weakness                  1
neck weakness                   1
Length: 268, dtype: int64

In [7]:
df = df.fillna(0)

In [8]:
print(df.isnull().sum().sum())

0

In [9]:
X = df.drop("diseases", axis=1)
y = df["diseases"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (50238, 377)
Target Shape: (50238,)

In [10]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_encoded = label_encoder.fit_transform(y)

print("Total Diseases:", len(label_encoder.classes_))
print("First 10 Encoded Labels:", y_encoded[:10])

Total Diseases: 227
First 10 Encoded Labels: [159 159 159 159 159 159 159 159 159 159]

In [11]:
disease_counts = df["diseases"].value_counts()

print(disease_counts)

diseases
vulvodynia                        1218
complex regional pain syndrome    1217
spondylosis                       1216
hypoglycemia                      1215
infectious gastroenteritis        1212
                                  ...
pulmonic valve disease               1
diabetes                             1
open wound of the chest              1
huntington disease                   1
insulin overdose                     1
Name: count, Length: 227, dtype: int64

In [12]:
print(disease_counts[disease_counts < 2])

diseases
turner syndrome            1
dengue fever               1
hashimoto thyroiditis      1
cryptococcosis             1
pulmonic valve disease     1
diabetes                   1
open wound of the chest    1
huntington disease         1
insulin overdose           1
Name: count, dtype: int64

In [13]:
valid_diseases = disease_counts[disease_counts >= 2].index

df = df[df["diseases"].isin(valid_diseases)]

print(df.shape)

(50229, 378)

In [14]:
X = df.drop("diseases", axis=1)
y = df["diseases"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (50229, 377)
Target Shape: (50229,)

In [15]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_encoded = label_encoder.fit_transform(y)

print("Total Diseases:", len(label_encoder.classes_))

Total Diseases: 218

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

print("Training Shape :", X_train.shape)
print("Testing Shape  :", X_test.shape)

Training Shape : (40183, 377)
Testing Shape  : (10046, 377)

In [26]:
model = XGBClassifier(
    objective="multi:softprob",
    num_class=len(label_encoder.classes_),
    n_estimators=20,
    max_depth=4,
    learning_rate=0.3,
    tree_method="hist",
    random_state=42,
    eval_metric="mlogloss",
    n_jobs=2
)

In [27]:
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.3, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=20, n_jobs=2, num_class=218, ...)

In [23]:
import xgboost
print(xgboost.__version__)

3.3.0

In [24]:
import multiprocessing

print("CPU Cores:", multiprocessing.cpu_count())

CPU Cores: 2

In [25]:
print(X_train.shape)
print(y_train.shape)
print(len(label_encoder.classes_))

(40183, 377)
(40183,)
218

In [28]:
y_pred = model.predict(X_test)

In [29]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9034441568783595

In [30]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred, average="weighted", zero_division=0)
recall = recall_score(y_test, y_pred, average="weighted", zero_division=0)
f1 = f1_score(y_test, y_pred, average="weighted", zero_division=0)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

Accuracy : 0.9034441568783595
Precision: 0.9016312292789469
Recall   : 0.9034441568783595
F1 Score : 0.9011397646434735

In [32]:
from sklearn.metrics import classification_report
import numpy as np

labels = np.unique(np.concatenate([y_test, y_pred]))

print(classification_report(
    y_test,
    y_pred,
    labels=labels,
    target_names=label_encoder.inverse_transform(labels),
    zero_division=0
))

                                                          precision    recall  f1-score   support

                                        abdominal hernia       0.98      0.98      0.98        53
                                     abscess of the lung       0.00      0.00      0.00         1
                                               achalasia       0.50      0.60      0.55         5
                                       actinic keratosis       0.92      0.93      0.92       162
                                      acute bronchospasm       0.85      0.78      0.81       162
                                          acute glaucoma       0.63      0.63      0.63        30
                                      acute otitis media       0.93      0.93      0.93       107
                                      acute pancreatitis       0.97      0.98      0.97       242
                                         acute sinusitis       0.91      0.90      0.91       166
                                                 allergy       0.98      0.99      0.99       161
                                                alopecia       0.79      0.77      0.78        35
                                            anal fissure       0.96      0.93      0.95        28
                    anemia due to chronic kidney disease       0.78      1.00      0.88         7
                                                  asthma       0.82      0.79      0.80       163
                                             astigmatism       0.64      0.68      0.66        31
                                             atelectasis       1.00      0.71      0.83         7
                                     atrial fibrillation       0.88      0.50      0.64        14
                                      atrophic vaginitis       0.94      0.91      0.92        32
         attention deficit hyperactivity disorder (adhd)       0.95      0.92      0.93        62
                                      benign kidney cyst       0.79      0.83      0.81        18
                                        bipolar disorder       0.85      0.90      0.87       107
                                          bladder cancer       0.92      0.92      0.92        13
                                        bladder disorder       0.91      0.84      0.87        61
                                             bone cancer       1.00      0.50      0.67         4
                             bone spur of the calcaneous       1.00      0.33      0.50         3
                                                bursitis       0.97      0.98      0.98       242
                               carbon monoxide poisoning       0.83      0.71      0.77         7
                          cellulitis or abscess of mouth       1.00      1.00      1.00        12
                                          cerebral palsy       0.89      0.89      0.89         9
                                               chalazion       0.94      0.96      0.95       105
                                     choledocholithiasis       0.93      0.95      0.94        58
                                           cholesteatoma       0.00      0.00      0.00         1
                                         chorioretinitis       0.50      0.75      0.60         4
chronic inflammatory demyelinating polyneuropathy (cidp)       0.00      0.00      0.00         1
                                  chronic kidney disease       0.00      0.00      0.00         2
            chronic obstructive pulmonary disease (copd)       0.79      0.83      0.81       162
                                    chronic otitis media       0.97      0.96      0.97       104
                                   chronic pain disorder       0.88      0.86      0.87       106
                                       chronic sinusitis       0.85      0.92      0.89       101
                                               cirrhosis       0.94      0.97      0.96        33
                         coagulation (bleeding) disorder       1.00      1.00      1.00         5
                                           colonic polyp       0.90      0.82      0.86        34
                          complex regional pain syndrome       0.94      0.95      0.94       244
                                              concussion       0.97      1.00      0.98       238
                                 conductive hearing loss       0.98      0.92      0.95        97
                                     conversion disorder       0.00      0.00      0.00         1
                                        cornea infection       0.95      0.87      0.91       163
                                        corneal disorder       0.75      0.73      0.74       105
                                coronary atherosclerosis       0.90      0.95      0.93        20
                                     cranial nerve palsy       1.00      0.97      0.99        34
                                         crushing injury       0.50      0.57      0.53         7
                                          cryptorchidism       0.00      0.00      0.00         1
                                           cysticercosis       0.00      0.00      0.00         2
                              deep vein thrombosis (dvt)       1.00      0.89      0.94        18
                               degenerative disc disease       0.75      0.82      0.78       162
                          dermatitis due to sun exposure       0.86      0.75      0.80        59
                                    diabetic retinopathy       0.78      0.68      0.73        59
                                dislocation of the ankle       0.00      0.00      0.00         2
                                dislocation of the elbow       0.75      0.92      0.83        13
                                 dislocation of the foot       0.00      0.00      0.00         1
                                          diverticulosis       0.91      0.96      0.93       104
                                         eating disorder       0.97      0.95      0.96        60
                                               emphysema       0.00      0.00      0.00         1
                                                 empyema       0.00      0.00      0.00         1
                                           endometriosis       0.94      0.96      0.95        53
                                         endophthalmitis       0.83      0.71      0.77         7
                                       esophageal cancer       0.60      0.75      0.67         4
                          extrapyramidal effect of drugs       1.00      0.67      0.80         6
                                  eye alignment disorder       0.98      0.98      0.98        58
                     female infertility of unknown cause       0.00      0.00      0.00         3
                                  fetal alcohol syndrome       0.00      0.00      0.00         1
                                            fibromyalgia       0.73      0.79      0.76       101
                                               flat feet       1.00      0.67      0.80         3
                                 foreign body in the ear       0.75      0.75      0.75         4
              foreign body in the gastrointestinal tract       1.00      0.78      0.88         9
                              foreign body in the vagina       0.00      0.00      0.00         1
                                     fracture of the arm       0.94      0.95      0.94        78
                                  fracture of the finger       0.00      0.00      0.00         2
                                    fracture of the hand       0.82      0.70      0.76        20
                            fungal infection of the skin       0.81      0.90      0.85       107
                  gastroesophageal reflux disease (gerd)       0.83      0.95      0.88        60
                                                glaucoma       0.58      0.81      0.68        63
                          headache after lumbar puncture       1.00      0.80      0.89        15
                                             heart block       0.89      0.97      0.93        95
                                            hemarthrosis       0.00      0.00      0.00         1
                                  hepatic encephalopathy       1.00      1.00      1.00         4
                                              herpangina       0.97      0.97      0.97        60
                                           hiatal hernia       0.98      0.96      0.97       163
                                    hirschsprung disease       0.00      0.00      0.00         1
                                               hirsutism       0.00      0.00      0.00         1
                               hydrocele of the testicle       0.97      1.00      0.98        28
                                          hydronephrosis       0.76      0.85      0.80        33
                                           hypercalcemia       0.00      0.00      0.00         1
                                           hyperhidrosis       0.00      0.00      0.00         2
                                            hyperkalemia       0.97      0.98      0.98       101
                                               hyperopia       1.00      0.86      0.92         7
          hypertrophic obstructive cardiomyopathy (hocm)       0.00      0.00      0.00         1
                                            hypoglycemia       0.97      1.00      0.99       243
                                          hypothyroidism       1.00      0.57      0.73         7
                      idiopathic absence of menstruation       0.98      0.98      0.98        58
                        idiopathic nonmenstrual bleeding       1.00      1.00      1.00         5
                                             indigestion       0.94      0.84      0.89        58
                                        induced abortion       0.94      0.97      0.95        31
                                 infection of open wound       0.00      0.00      0.00         1
                              infectious gastroenteritis       0.97      0.98      0.97       243
                                        ingrown toe nail       0.98      0.98      0.98        94
                                injury to internal organ       1.00      0.71      0.83         7
                                   injury to the abdomen       0.50      0.33      0.40         3
                                       injury to the arm       0.96      0.96      0.96       242
                                    injury to the finger       0.00      0.00      0.00         1
                                      injury to the hand       0.71      0.86      0.77        14
                                       injury to the hip       0.00      0.00      0.00         2
                                      injury to the knee       1.00      0.75      0.86         4
                                       injury to the leg       0.96      0.99      0.98       241
                                  injury to the shoulder       0.97      0.95      0.96        63
                                     injury to the trunk       0.99      0.96      0.97       161
                                intestinal malabsorption       0.92      0.85      0.88        13
                                 intracranial hemorrhage       0.82      0.90      0.86        30
                                   ischemia of the bowel       0.77      0.89      0.83        19
                           juvenile rheumatoid arthritis       0.00      0.00      0.00         3
                                                    lice       0.00      0.00      0.00         3
                                            liver cancer       1.00      0.50      0.67         4
                                          lung contusion       0.00      0.00      0.00         1
                                              lymphedema       0.95      0.98      0.97        63
                                                lymphoma       1.00      1.00      1.00         8
                                    magnesium deficiency       0.00      0.00      0.00         1
                                         marijuana abuse       0.95      0.94      0.95       242
                                             mastoiditis       0.67      0.44      0.53         9
                                         meniere disease       0.85      0.91      0.88        32
                                      metabolic disorder       0.00      0.00      0.00         2
                                    mitral valve disease       0.91      0.95      0.93        44
                                           mononucleosis       0.91      0.91      0.91        32
                                       myasthenia gravis       0.82      0.90      0.86        10
                                               myoclonus       0.00      0.00      0.00         1
                                                myositis       0.60      0.38      0.46         8
                                       neonatal jaundice       0.00      0.00      0.00         3
                                               neuralgia       0.58      0.65      0.61       106
                       nonalcoholic liver disease (nash)       1.00      0.75      0.86         4
                           normal pressure hydrocephalus       0.00      0.00      0.00         1
                                  open wound of the back       0.00      0.00      0.00         1
                                 open wound of the mouth       1.00      1.00      1.00         6
                                  open wound of the neck       0.00      0.00      0.00         3
                                      orbital cellulitis       0.94      1.00      0.97        16
                                         osteochondrosis       0.88      0.88      0.88         8
                                            otosclerosis       0.00      0.00      0.00         1
                                         ovarian torsion       0.71      0.71      0.71         7
                                 pain after an operation       0.90      0.93      0.91       161
                                            panic attack       0.77      0.77      0.77        13
                                          panic disorder       0.98      0.94      0.96       162
                                   pelvic organ prolapse       0.85      0.90      0.87        58
                                            pericarditis       1.00      0.75      0.86         8
                                             peritonitis       0.91      0.81      0.85        36
                                        peyronie disease       0.00      0.00      0.00         2
                                          pilonidal cyst       0.97      0.91      0.94        34
                                       pinworm infection       1.00      0.86      0.92         7
                                       pituitary adenoma       0.33      0.50      0.40         2
                                       plantar fasciitis       1.00      0.94      0.97        17
                             poisoning due to analgesics       1.00      0.86      0.92         7
                        poisoning due to antidepressants       0.00      0.00      0.00         2
                    poisoning due to antimicrobial drugs       1.00      0.71      0.83         7
                        poisoning due to ethylene glycol       0.00      0.00      0.00         1
                              poisoning due to sedatives       0.62      0.56      0.59         9
                               polycystic kidney disease       0.88      0.88      0.88        24
                                  polymyalgia rheumatica       1.00      0.78      0.88         9
                                   postpartum depression       0.97      0.97      0.97        61
                           premenstrual tension syndrome       0.89      1.00      0.94         8
                                            presbyacusis       0.60      0.60      0.60         5
                                                priapism       0.00      0.00      0.00         1
                                        primary insomnia       0.88      0.93      0.90        15
                                problem during pregnancy       0.97      0.99      0.98       164
                                      protein deficiency       1.00      1.00      1.00         3
                                               pterygium       0.67      0.67      0.67        15
                                    pulmonary congestion       0.88      0.93      0.90        61
                                  pulmonary eosinophilia       1.00      0.94      0.97        17
                                      pulmonary fibrosis       0.55      0.85      0.67        13
                                          pyelonephritis       0.87      0.93      0.90       161
                                        pyloric stenosis       0.00      0.00      0.00         1
                                   restless leg syndrome       0.94      1.00      0.97        31
                  retinopathy due to high blood pressure       0.80      0.44      0.57         9
                                     rotator cuff injury       1.00      1.00      1.00         8
                                 salivary gland disorder       0.00      0.00      0.00         2
                                                sciatica       0.97      0.96      0.97       104
                                               scleritis       0.67      0.67      0.67         3
                                             scleroderma       0.89      0.91      0.90        34
                                     sick sinus syndrome       0.77      0.71      0.74        24
                                             spondylitis       1.00      0.95      0.97        58
                                             spondylosis       0.80      0.75      0.77       243
                                     stress incontinence       0.84      0.89      0.86        18
                                                  stroke       0.93      0.94      0.93        96
                                     subdural hemorrhage       0.88      0.78      0.82         9
                       substance-related mental disorder       0.67      0.89      0.76        18
      syndrome of inappropriate secretion of adh (siadh)       0.00      0.00      0.00         1
                                           syringomyelia       0.00      0.00      0.00         1
                                       teething syndrome       0.98      0.97      0.97        58
                                thoracic aortic aneurysm       0.88      0.88      0.88        17
                                        thrombophlebitis       0.95      0.97      0.96        58
                                         tietze syndrome       0.94      0.85      0.89        34
                               tinnitus of unknown cause       0.78      0.88      0.82        32
                               transient ischemic attack       0.97      0.94      0.96       105
                                      tuberous sclerosis       0.00      0.00      0.00         1
                                         urethral valves       0.50      0.33      0.40         3
                                        uterine fibroids       0.95      0.97      0.96        58
                                 vaginal yeast infection       0.83      0.89      0.86        99

In [33]:
from sklearn.metrics import classification_report
import numpy as np

labels = np.unique(np.concatenate([y_test, y_pred]))

print(classification_report(
    y_test,
    y_pred,
    labels=labels,
    target_names=label_encoder.inverse_transform(labels),
    zero_division=0
))

                                                          precision    recall  f1-score   support

                                        abdominal hernia       0.98      0.98      0.98        53
                                     abscess of the lung       0.00      0.00      0.00         1
                                               achalasia       0.50      0.60      0.55         5
                                       actinic keratosis       0.92      0.93      0.92       162
                                      acute bronchospasm       0.85      0.78      0.81       162
                                          acute glaucoma       0.63      0.63      0.63        30
                                      acute otitis media       0.93      0.93      0.93       107
                                      acute pancreatitis       0.97      0.98      0.97       242
                                         acute sinusitis       0.91      0.90      0.91       166
                                                 allergy       0.98      0.99      0.99       161
                                                alopecia       0.79      0.77      0.78        35
                                            anal fissure       0.96      0.93      0.95        28
                    anemia due to chronic kidney disease       0.78      1.00      0.88         7
                                                  asthma       0.82      0.79      0.80       163
                                             astigmatism       0.64      0.68      0.66        31
                                             atelectasis       1.00      0.71      0.83         7
                                     atrial fibrillation       0.88      0.50      0.64        14
                                      atrophic vaginitis       0.94      0.91      0.92        32
         attention deficit hyperactivity disorder (adhd)       0.95      0.92      0.93        62
                                      benign kidney cyst       0.79      0.83      0.81        18
                                        bipolar disorder       0.85      0.90      0.87       107
                                          bladder cancer       0.92      0.92      0.92        13
                                        bladder disorder       0.91      0.84      0.87        61
                                             bone cancer       1.00      0.50      0.67         4
                             bone spur of the calcaneous       1.00      0.33      0.50         3
                                                bursitis       0.97      0.98      0.98       242
                               carbon monoxide poisoning       0.83      0.71      0.77         7
                          cellulitis or abscess of mouth       1.00      1.00      1.00        12
                                          cerebral palsy       0.89      0.89      0.89         9
                                               chalazion       0.94      0.96      0.95       105
                                     choledocholithiasis       0.93      0.95      0.94        58
                                           cholesteatoma       0.00      0.00      0.00         1
                                         chorioretinitis       0.50      0.75      0.60         4
chronic inflammatory demyelinating polyneuropathy (cidp)       0.00      0.00      0.00         1
                                  chronic kidney disease       0.00      0.00      0.00         2
            chronic obstructive pulmonary disease (copd)       0.79      0.83      0.81       162
                                    chronic otitis media       0.97      0.96      0.97       104
                                   chronic pain disorder       0.88      0.86      0.87       106
                                       chronic sinusitis       0.85      0.92      0.89       101
                                               cirrhosis       0.94      0.97      0.96        33
                         coagulation (bleeding) disorder       1.00      1.00      1.00         5
                                           colonic polyp       0.90      0.82      0.86        34
                          complex regional pain syndrome       0.94      0.95      0.94       244
                                              concussion       0.97      1.00      0.98       238
                                 conductive hearing loss       0.98      0.92      0.95        97
                                     conversion disorder       0.00      0.00      0.00         1
                                        cornea infection       0.95      0.87      0.91       163
                                        corneal disorder       0.75      0.73      0.74       105
                                coronary atherosclerosis       0.90      0.95      0.93        20
                                     cranial nerve palsy       1.00      0.97      0.99        34
                                         crushing injury       0.50      0.57      0.53         7
                                          cryptorchidism       0.00      0.00      0.00         1
                                           cysticercosis       0.00      0.00      0.00         2
                              deep vein thrombosis (dvt)       1.00      0.89      0.94        18
                               degenerative disc disease       0.75      0.82      0.78       162
                          dermatitis due to sun exposure       0.86      0.75      0.80        59
                                    diabetic retinopathy       0.78      0.68      0.73        59
                                dislocation of the ankle       0.00      0.00      0.00         2
                                dislocation of the elbow       0.75      0.92      0.83        13
                                 dislocation of the foot       0.00      0.00      0.00         1
                                          diverticulosis       0.91      0.96      0.93       104
                                         eating disorder       0.97      0.95      0.96        60
                                               emphysema       0.00      0.00      0.00         1
                                                 empyema       0.00      0.00      0.00         1
                                           endometriosis       0.94      0.96      0.95        53
                                         endophthalmitis       0.83      0.71      0.77         7
                                       esophageal cancer       0.60      0.75      0.67         4
                          extrapyramidal effect of drugs       1.00      0.67      0.80         6
                                  eye alignment disorder       0.98      0.98      0.98        58
                     female infertility of unknown cause       0.00      0.00      0.00         3
                                  fetal alcohol syndrome       0.00      0.00      0.00         1
                                            fibromyalgia       0.73      0.79      0.76       101
                                               flat feet       1.00      0.67      0.80         3
                                 foreign body in the ear       0.75      0.75      0.75         4
              foreign body in the gastrointestinal tract       1.00      0.78      0.88         9
                              foreign body in the vagina       0.00      0.00      0.00         1
                                     fracture of the arm       0.94      0.95      0.94        78
                                  fracture of the finger       0.00      0.00      0.00         2
                                    fracture of the hand       0.82      0.70      0.76        20
                            fungal infection of the skin       0.81      0.90      0.85       107
                  gastroesophageal reflux disease (gerd)       0.83      0.95      0.88        60
                                                glaucoma       0.58      0.81      0.68        63
                          headache after lumbar puncture       1.00      0.80      0.89        15
                                             heart block       0.89      0.97      0.93        95
                                            hemarthrosis       0.00      0.00      0.00         1
                                  hepatic encephalopathy       1.00      1.00      1.00         4
                                              herpangina       0.97      0.97      0.97        60
                                           hiatal hernia       0.98      0.96      0.97       163
                                    hirschsprung disease       0.00      0.00      0.00         1
                                               hirsutism       0.00      0.00      0.00         1
                               hydrocele of the testicle       0.97      1.00      0.98        28
                                          hydronephrosis       0.76      0.85      0.80        33
                                           hypercalcemia       0.00      0.00      0.00         1
                                           hyperhidrosis       0.00      0.00      0.00         2
                                            hyperkalemia       0.97      0.98      0.98       101
                                               hyperopia       1.00      0.86      0.92         7
          hypertrophic obstructive cardiomyopathy (hocm)       0.00      0.00      0.00         1
                                            hypoglycemia       0.97      1.00      0.99       243
                                          hypothyroidism       1.00      0.57      0.73         7
                      idiopathic absence of menstruation       0.98      0.98      0.98        58
                        idiopathic nonmenstrual bleeding       1.00      1.00      1.00         5
                                             indigestion       0.94      0.84      0.89        58
                                        induced abortion       0.94      0.97      0.95        31
                                 infection of open wound       0.00      0.00      0.00         1
                              infectious gastroenteritis       0.97      0.98      0.97       243
                                        ingrown toe nail       0.98      0.98      0.98        94
                                injury to internal organ       1.00      0.71      0.83         7
                                   injury to the abdomen       0.50      0.33      0.40         3
                                       injury to the arm       0.96      0.96      0.96       242
                                    injury to the finger       0.00      0.00      0.00         1
                                      injury to the hand       0.71      0.86      0.77        14
                                       injury to the hip       0.00      0.00      0.00         2
                                      injury to the knee       1.00      0.75      0.86         4
                                       injury to the leg       0.96      0.99      0.98       241
                                  injury to the shoulder       0.97      0.95      0.96        63
                                     injury to the trunk       0.99      0.96      0.97       161
                                intestinal malabsorption       0.92      0.85      0.88        13
                                 intracranial hemorrhage       0.82      0.90      0.86        30
                                   ischemia of the bowel       0.77      0.89      0.83        19
                           juvenile rheumatoid arthritis       0.00      0.00      0.00         3
                                                    lice       0.00      0.00      0.00         3
                                            liver cancer       1.00      0.50      0.67         4
                                          lung contusion       0.00      0.00      0.00         1
                                              lymphedema       0.95      0.98      0.97        63
                                                lymphoma       1.00      1.00      1.00         8
                                    magnesium deficiency       0.00      0.00      0.00         1
                                         marijuana abuse       0.95      0.94      0.95       242
                                             mastoiditis       0.67      0.44      0.53         9
                                         meniere disease       0.85      0.91      0.88        32
                                      metabolic disorder       0.00      0.00      0.00         2
                                    mitral valve disease       0.91      0.95      0.93        44
                                           mononucleosis       0.91      0.91      0.91        32
                                       myasthenia gravis       0.82      0.90      0.86        10
                                               myoclonus       0.00      0.00      0.00         1
                                                myositis       0.60      0.38      0.46         8
                                       neonatal jaundice       0.00      0.00      0.00         3
                                               neuralgia       0.58      0.65      0.61       106
                       nonalcoholic liver disease (nash)       1.00      0.75      0.86         4
                           normal pressure hydrocephalus       0.00      0.00      0.00         1
                                  open wound of the back       0.00      0.00      0.00         1
                                 open wound of the mouth       1.00      1.00      1.00         6
                                  open wound of the neck       0.00      0.00      0.00         3
                                      orbital cellulitis       0.94      1.00      0.97        16
                                         osteochondrosis       0.88      0.88      0.88         8
                                            otosclerosis       0.00      0.00      0.00         1
                                         ovarian torsion       0.71      0.71      0.71         7
                                 pain after an operation       0.90      0.93      0.91       161
                                            panic attack       0.77      0.77      0.77        13
                                          panic disorder       0.98      0.94      0.96       162
                                   pelvic organ prolapse       0.85      0.90      0.87        58
                                            pericarditis       1.00      0.75      0.86         8
                                             peritonitis       0.91      0.81      0.85        36
                                        peyronie disease       0.00      0.00      0.00         2
                                          pilonidal cyst       0.97      0.91      0.94        34
                                       pinworm infection       1.00      0.86      0.92         7
                                       pituitary adenoma       0.33      0.50      0.40         2
                                       plantar fasciitis       1.00      0.94      0.97        17
                             poisoning due to analgesics       1.00      0.86      0.92         7
                        poisoning due to antidepressants       0.00      0.00      0.00         2
                    poisoning due to antimicrobial drugs       1.00      0.71      0.83         7
                        poisoning due to ethylene glycol       0.00      0.00      0.00         1
                              poisoning due to sedatives       0.62      0.56      0.59         9
                               polycystic kidney disease       0.88      0.88      0.88        24
                                  polymyalgia rheumatica       1.00      0.78      0.88         9
                                   postpartum depression       0.97      0.97      0.97        61
                           premenstrual tension syndrome       0.89      1.00      0.94         8
                                            presbyacusis       0.60      0.60      0.60         5
                                                priapism       0.00      0.00      0.00         1
                                        primary insomnia       0.88      0.93      0.90        15
                                problem during pregnancy       0.97      0.99      0.98       164
                                      protein deficiency       1.00      1.00      1.00         3
                                               pterygium       0.67      0.67      0.67        15
                                    pulmonary congestion       0.88      0.93      0.90        61
                                  pulmonary eosinophilia       1.00      0.94      0.97        17
                                      pulmonary fibrosis       0.55      0.85      0.67        13
                                          pyelonephritis       0.87      0.93      0.90       161
                                        pyloric stenosis       0.00      0.00      0.00         1
                                   restless leg syndrome       0.94      1.00      0.97        31
                  retinopathy due to high blood pressure       0.80      0.44      0.57         9
                                     rotator cuff injury       1.00      1.00      1.00         8
                                 salivary gland disorder       0.00      0.00      0.00         2
                                                sciatica       0.97      0.96      0.97       104
                                               scleritis       0.67      0.67      0.67         3
                                             scleroderma       0.89      0.91      0.90        34
                                     sick sinus syndrome       0.77      0.71      0.74        24
                                             spondylitis       1.00      0.95      0.97        58
                                             spondylosis       0.80      0.75      0.77       243
                                     stress incontinence       0.84      0.89      0.86        18
                                                  stroke       0.93      0.94      0.93        96
                                     subdural hemorrhage       0.88      0.78      0.82         9
                       substance-related mental disorder       0.67      0.89      0.76        18
      syndrome of inappropriate secretion of adh (siadh)       0.00      0.00      0.00         1
                                           syringomyelia       0.00      0.00      0.00         1
                                       teething syndrome       0.98      0.97      0.97        58
                                thoracic aortic aneurysm       0.88      0.88      0.88        17
                                        thrombophlebitis       0.95      0.97      0.96        58
                                         tietze syndrome       0.94      0.85      0.89        34
                               tinnitus of unknown cause       0.78      0.88      0.82        32
                               transient ischemic attack       0.97      0.94      0.96       105
                                      tuberous sclerosis       0.00      0.00      0.00         1
                                         urethral valves       0.50      0.33      0.40         3
                                        uterine fibroids       0.95      0.97      0.96        58
                                 vaginal yeast infection       0.83      0.89      0.86        99

In [34]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix Shape:", cm.shape)

Confusion Matrix Shape: (212, 212)

In [35]:
print(cm)

[[ 52   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   3 ...   0   0   0]
 ...
 [  0   0   0 ...   2   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0 238]]

In [36]:
import pandas as pd

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance.head(20)

                                    Feature  Importance
261                         eyelid swelling    0.080678
41                 white discharge from eye    0.072667
326                            leg weakness    0.066000
235                         pulling at ears    0.057354
248  muscle cramps, contractures, or spasms    0.057053
156                            itchy eyelid    0.051215
105                     symptoms of infants    0.049000
315                     antisocial behavior    0.048575
135                       difficulty eating    0.047233
187                         swollen abdomen    0.047115
88                     eye moves abnormally    0.046973
277                          bumps on penis    0.041662
314              obsessions and compulsions    0.032994
247                      stiffness all over    0.031986
139                       vulvar irritation    0.030705
155                     eye burns or stings    0.023755
209              pain or soreness of breast    0.023606
259                          mass on eyelid    0.018626
272                             itchy scalp    0.018510
11                           breathing fast    0.017582

In [37]:
import joblib

joblib.dump(model, "xgboost_model.pkl")

print("Model Saved Successfully!")

Model Saved Successfully!

In [38]:
joblib.dump(label_encoder, "label_encoder.pkl")

print("Label Encoder Saved Successfully!")

Label Encoder Saved Successfully!

In [39]:
sample = X.iloc[[0]]

prediction = model.predict(sample)

predicted_disease = label_encoder.inverse_transform(prediction)

print("Predicted Disease:", predicted_disease[0])

Predicted Disease: panic disorder

In [40]:
actual = y.iloc[0]

print("Actual Disease   :", actual)
print("Predicted Disease:", predicted_disease[0])

Actual Disease   : panic disorder
Predicted Disease: panic disorder