In [1]:
import pandas as pd
import numpy as np

In [2]:
print("MedAssist AI Dataset Analysis Started")

MedAssist AI Dataset Analysis Started

In [3]:
import os
os.getcwd()

'C:\\Users\\admin'

In [6]:
import os

os.chdir(r"C:\Users\admin\Desktop\MedAssist AI")

print(os.getcwd())

C:\Users\admin\Desktop\MedAssist AI

In [7]:
import os

os.listdir()

['cleaned_data',
 'datasets',
 'images',
 'models',
 'notesbooks',
 'README.md',
 'reports']

In [8]:
os.listdir("datasets")

['Dataset_1_SympScan',
 'Dataset_2_DiseasePrediction',
 'Dataset_3_SymptomsToDisease']

In [9]:
os.listdir("datasets/Dataset_1_SympScan")

['description.csv',
 'diets.csv',
 'Diseases_and_Symptoms_dataset.csv',
 'medications.csv',
 'precautions.csv',
 'workout.csv']

In [10]:
sympscan = pd.read_csv("datasets/Dataset_1_SympScan/Diseases_and_Symptoms_dataset.csv")

In [11]:
sympscan.head()

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,sneezing,leg weakness,hysterical behavior,arm lump or mass,bleeding gums,pain in gums,diaper rash,hesitancy,back stiffness or tightness,low urine output
0,panic disorder,1,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,panic disorder,0,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,panic disorder,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,panic disorder,1,0,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,panic disorder,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [12]:
sympscan.shape

(96088, 231)

In [13]:
sympscan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96088 entries, 0 to 96087
Columns: 231 entries, diseases to low urine output
dtypes: int64(230), object(1)
memory usage: 169.3+ MB

In [14]:
sympscan.describe(include='all')

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,sneezing,leg weakness,hysterical behavior,arm lump or mass,bleeding gums,pain in gums,diaper rash,hesitancy,back stiffness or tightness,low urine output
count,96088,96088.000000,96088.000000,96088.000000,96088.000000,96088.000000,96088.000000,96088.000000,96088.000000,96088.000000,...,96088.000000,96088.000000,96088.000000,96088.000000,96088.000000,96088.000000,96088.000000,96088.000000,96088.000000,96088.000000
unique,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,cystitis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,0.028994,0.029900,0.097588,0.041087,0.098285,0.062661,0.035270,0.041389,0.045510,...,0.010886,0.015486,0.004433,0.004184,0.004215,0.010355,0.004433,0.006223,0.004267,0.006296
std,NaN,0.167791,0.170311,0.296758,0.198493,0.297701,0.242354,0.184462,0.199190,0.208422,...,0.103766,0.123475,0.066437,0.064546,0.064786,0.101232,0.066437,0.078643,0.065183,0.079100
min,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [15]:
sympscan.isnull().sum()

diseases                            0
anxiety and nervousness             0
depression                          0
shortness of breath                 0
depressive or psychotic symptoms    0
                                   ..
pain in gums                        0
diaper rash                         0
hesitancy                           0
back stiffness or tightness         0
low urine output                    0
Length: 231, dtype: int64

In [16]:
sympscan.duplicated().sum()

np.int64(0)

In [18]:
sympscan["diseases"].nunique()

100

In [19]:
sympscan.head(10)

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,sneezing,leg weakness,hysterical behavior,arm lump or mass,bleeding gums,pain in gums,diaper rash,hesitancy,back stiffness or tightness,low urine output
0,panic disorder,1,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,panic disorder,0,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,panic disorder,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,panic disorder,1,0,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,panic disorder,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
5,panic disorder,0,0,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
6,panic disorder,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,panic disorder,0,0,0,1,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
8,panic disorder,1,0,0,1,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
9,panic disorder,1,1,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
list(sympscan.columns)

['diseases',
 'anxiety and nervousness',
 'depression',
 'shortness of breath',
 'depressive or psychotic symptoms',
 'sharp chest pain',
 'dizziness',
 'insomnia',
 'abnormal involuntary movements',
 'chest tightness',
 'palpitations',
 'irregular heartbeat',
 'breathing fast',
 'hoarse voice',
 'sore throat',
 'difficulty speaking',
 'cough',
 'nasal congestion',
 'throat swelling',
 'diminished hearing',
 'difficulty in swallowing',
 'skin swelling',
 'retention of urine',
 'leg pain',
 'hip pain',
 'suprapubic pain',
 'blood in stool',
 'lack of growth',
 'symptoms of the scrotum and testes',
 'swelling of scrotum',
 'pain in testicles',
 'pus draining from ear',
 'jaundice',
 'white discharge from eye',
 'irritable infant',
 'abusing alcohol',
 'fainting',
 'hostile behavior',
 'drug abuse',
 'sharp abdominal pain',
 'feeling ill',
 'vomiting',
 'headache',
 'nausea',
 'diarrhea',
 'vaginal itching',
 'painful urination',
 'involuntary urination',
 'pain during intercourse',
 'frequent urination',
 'lower abdominal pain',
 'vaginal discharge',
 'blood in urine',
 'hot flashes',
 'intermenstrual bleeding',
 'hand or finger pain',
 'wrist pain',
 'hand or finger swelling',
 'arm pain',
 'wrist swelling',
 'arm stiffness or tightness',
 'arm swelling',
 'hand or finger stiffness or tightness',
 'lip swelling',
 'toothache',
 'abnormal appearing skin',
 'skin lesion',
 'acne or pimples',
 'facial pain',
 'mouth ulcer',
 'skin growth',
 'diminished vision',
 'double vision',
 'symptoms of eye',
 'pain in eye',
 'abnormal movement of eyelid',
 'foreign body sensation in eye',
 'irregular appearing scalp',
 'back pain',
 'neck pain',
 'low back pain',
 'pain of the anus',
 'pain during pregnancy',
 'pelvic pain',
 'impotence',
 'vomiting blood',
 'regurgitation',
 'burning abdominal pain',
 'restlessness',
 'wheezing',
 'peripheral edema',
 'neck mass',
 'ear pain',
 'jaw swelling',
 'mouth dryness',
 'neck swelling',
 'knee pain',
 'foot or toe pain',
 'ankle pain',
 'bones are painful',
 'elbow pain',
 'knee swelling',
 'skin moles',
 'weight gain',
 'problems with movement',
 'knee stiffness or tightness',
 'leg swelling',
 'foot or toe swelling',
 'heartburn',
 'infant feeding problem',
 'vaginal pain',
 'vaginal redness',
 'weakness',
 'decreased heart rate',
 'increased heart rate',
 'ringing in ear',
 'plugged feeling in ear',
 'itchy ear(s)',
 'frontal headache',
 'fluid in ear',
 'spots or clouds in vision',
 'eye redness',
 'lacrimation',
 'itchiness of eye',
 'blindness',
 'eye burns or stings',
 'decreased appetite',
 'excessive anger',
 'loss of sensation',
 'focal weakness',
 'symptoms of the face',
 'disturbance of memory',
 'paresthesia',
 'side pain',
 'fever',
 'shoulder pain',
 'shoulder stiffness or tightness',
 'ache all over',
 'lower body pain',
 'problems during pregnancy',
 'spotting or bleeding during pregnancy',
 'cramps and spasms',
 'upper abdominal pain',
 'stomach bloating',
 'changes in stool appearance',
 'unusual color or odor to urine',
 'kidney mass',
 'symptoms of prostate',
 'difficulty breathing',
 'rib pain',
 'joint pain',
 'hand or finger lump or mass',
 'chills',
 'groin pain',
 'fatigue',
 'regurgitation.1',
 'symptoms of the kidneys',
 'melena',
 'coughing up sputum',
 'seizures',
 'delusions or hallucinations',
 'excessive urination at night',
 'bleeding from eye',
 'rectal bleeding',
 'constipation',
 'temper problems',
 'coryza',
 'hemoptysis',
 'allergic reaction',
 'congestion in chest',
 'sleepiness',
 'apnea',
 'abnormal breathing sounds',
 'blood clots during menstrual periods',
 'pulling at ears',
 'gum pain',
 'redness in ear',
 'fluid retention',
 'flu-like syndrome',
 'sinus congestion',
 'painful sinuses',
 'fears and phobias',
 'recent pregnancy',
 'uterine contractions',
 'burning chest pain',
 'back cramps or spasms',
 'back mass or lump',
 'nosebleed',
 'long menstrual periods',
 'heavy menstrual flow',
 'unpredictable menstruation',
 'painful menstruation',
 'infertility',
 'frequent menstruation',
 'sweating',
 'mass on eyelid',
 'swollen eye',
 'eyelid swelling',
 'eyelid lesion or rash',
 'symptoms of bladder',
 'irregular appearing nails',
 'itching of skin',
 'hurts to breath',
 'skin dryness, peeling, scaliness, or roughness',
 'skin irritation',
 'itchy scalp',
 'warts',
 'skin rash',
 'mass or swelling around the anus',
 'ankle swelling',
 'elbow swelling',
 'bleeding from ear',
 'hand or finger weakness',
 'low self-esteem',
 'itching of the anus',
 'swollen or red tonsils',
 'hip stiffness or tightness',
 'mouth pain',
 'arm weakness',
 'obsessions and compulsions',
 'antisocial behavior',
 'sneezing',
 'leg weakness',
 'hysterical behavior',
 'arm lump or mass',
 'bleeding gums',
 'pain in gums',
 'diaper rash',
 'hesitancy',
 'back stiffness or tightness',
 'low urine output']

In [21]:
(sympscan.isnull().sum() / len(sympscan)) * 100

diseases                            0.0
anxiety and nervousness             0.0
depression                          0.0
shortness of breath                 0.0
depressive or psychotic symptoms    0.0
                                   ...
pain in gums                        0.0
diaper rash                         0.0
hesitancy                           0.0
back stiffness or tightness         0.0
low urine output                    0.0
Length: 231, dtype: float64

In [22]:
(sympscan == "").sum()

diseases                            0
anxiety and nervousness             0
depression                          0
shortness of breath                 0
depressive or psychotic symptoms    0
                                   ..
pain in gums                        0
diaper rash                         0
hesitancy                           0
back stiffness or tightness         0
low urine output                    0
Length: 231, dtype: int64

In [23]:
sympscan["diseases"].value_counts()

diseases
cystitis                              1219
vulvodynia                            1218
nose disorder                         1218
complex regional pain syndrome        1217
spondylosis                           1216
                                      ...
hypertensive heart disease             804
gum disease                            803
allergy                                803
injury to the trunk                    803
temporary or benign blood in urine     803
Name: count, Length: 100, dtype: int64

In [24]:
sympscan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96088 entries, 0 to 96087
Columns: 231 entries, diseases to low urine output
dtypes: int64(230), object(1)
memory usage: 169.3+ MB

In [25]:
sympscan.shape

(96088, 231)

In [26]:
disease_df = pd.read_csv("datasets/Dataset_1_SympScan/Diseases_and_Symptoms_dataset.csv")

description_df = pd.read_csv("datasets/Dataset_1_SympScan/description.csv")

medications_df = pd.read_csv("datasets/Dataset_1_SympScan/medications.csv")

precautions_df = pd.read_csv("datasets/Dataset_1_SympScan/precautions.csv")

diet_df = pd.read_csv("datasets/Dataset_1_SympScan/diets.csv")

workout_df = pd.read_csv("datasets/Dataset_1_SympScan/workout.csv")

In [27]:
print("Disease Dataset:", disease_df.shape)
print("Description Dataset:", description_df.shape)
print("Medication Dataset:", medications_df.shape)
print("Precautions Dataset:", precautions_df.shape)
print("Diet Dataset:", diet_df.shape)
print("Workout Dataset:", workout_df.shape)

Disease Dataset: (96088, 231)
Description Dataset: (100, 2)
Medication Dataset: (100, 2)
Precautions Dataset: (100, 5)
Diet Dataset: (100, 2)
Workout Dataset: (100, 2)

In [28]:
disease_df.head()

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,sneezing,leg weakness,hysterical behavior,arm lump or mass,bleeding gums,pain in gums,diaper rash,hesitancy,back stiffness or tightness,low urine output
0,panic disorder,1,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,panic disorder,0,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,panic disorder,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,panic disorder,1,0,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,panic disorder,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [29]:
description_df.head()

                    Disease                                        Description
0            Panic disorder  Panic disorder is a mental health condition ma...
1                 Vaginitis  Vaginitis is inflammation of the vaginal tissu...
2  Problem during pregnancy  Problems during pregnancy refer to medical com...
3        Acute pancreatitis  Acute pancreatitis is a sudden inflammation of...
4                    Asthma  Asthma is a chronic inflammatory disease of th...

In [30]:
medications_df.head()

                    Disease                                         Medication
0            Panic disorder  ['SSRIs (e.g., Sertraline, Fluoxetine)', 'Benz...
1                 Vaginitis  ['Metronidazole', 'Clindamycin', 'Fluconazole'...
2  Problem during pregnancy  ['Prenatal vitamins', 'Iron supplements', 'Ant...
3        Acute pancreatitis  ['IV fluids', 'Pain relievers (e.g., Morphine)...
4                    Asthma  ['Inhaled corticosteroids (e.g., Fluticasone)'...

In [31]:
precautions_df.head()

,Disease,Precaution_1,Precaution_2,Precaution_3,Precaution_4
0,Panic disorder,Practice deep breathing,Avoid caffeine,Follow therapy plan,Seek support from loved ones
1,Vaginitis,Wear breathable cotton underwear,Avoid douching,Maintain genital hygiene,Avoid scented hygiene products
2,Problem during pregnancy,Attend regular prenatal visits,Avoid alcohol and smoking,Eat a balanced diet,Get adequate rest
3,Acute pancreatitis,Avoid alcohol,Eat a low-fat diet,Stay hydrated,Follow doctor's advice strictly
4,Asthma,Avoid known triggers,Use inhaler as prescribed,Monitor peak flow,Keep emergency inhaler handy

In [32]:
diet_df.head()

                    Disease                                               Diet
0            Panic Disorder  ['Magnesium-rich foods (spinach, pumpkin seeds...
1                 Vaginitis  ['Probiotics (yogurt, kefir, sauerkraut)', 'Lo...
2  Problem During Pregnancy  ['Prenatal vitamins (consult doctor)', 'Iron-r...
3        Acute Pancreatitis  ['Low-fat foods (boiled vegetables, lean chick...
4                    Asthma  ['Anti-inflammatory foods (blueberries, kale, ...

In [33]:
workout_df.head()

                    Disease                                           Workouts
0            Panic disorder  ["Deep breathing exercises: Calm your mind by ...
1                 Vaginitis  ["Pelvic floor exercises: Strengthen pelvic mu...
2  Problem during pregnancy  ["Prenatal yoga: Gentle stretches safe for pre...
3        Acute pancreatitis  ["Avoid heavy lifting: Prevent strain on pancr...
4                    Asthma  ["Breathing exercises: Improve lung function",...

In [35]:
workout_df.duplicated().sum()

np.int64(0)

In [36]:
diet_df.duplicated().sum()

np.int64(0)

In [37]:
precautions_df.duplicated().sum()

np.int64(0)

In [38]:
medications_df.duplicated().sum()

np.int64(0)

In [39]:
description_df.duplicated().sum()

np.int64(0)

In [40]:
workout_df.isnull().sum()

Disease     0
Workouts    0
dtype: int64

In [41]:
diet_df.isnull().sum()

Disease    0
Diet       0
dtype: int64

In [42]:
precautions_df.isnull().sum()

Disease         0
Precaution_1    0
Precaution_2    0
Precaution_3    0
Precaution_4    0
dtype: int64

In [43]:
medications_df.isnull().sum()

Disease       0
Medication    0
dtype: int64

In [44]:
description_df.isnull().sum()

Disease        0
Description    0
dtype: int64

In [45]:
disease_df.columns.tolist()

['diseases',
 'anxiety and nervousness',
 'depression',
 'shortness of breath',
 'depressive or psychotic symptoms',
 'sharp chest pain',
 'dizziness',
 'insomnia',
 'abnormal involuntary movements',
 'chest tightness',
 'palpitations',
 'irregular heartbeat',
 'breathing fast',
 'hoarse voice',
 'sore throat',
 'difficulty speaking',
 'cough',
 'nasal congestion',
 'throat swelling',
 'diminished hearing',
 'difficulty in swallowing',
 'skin swelling',
 'retention of urine',
 'leg pain',
 'hip pain',
 'suprapubic pain',
 'blood in stool',
 'lack of growth',
 'symptoms of the scrotum and testes',
 'swelling of scrotum',
 'pain in testicles',
 'pus draining from ear',
 'jaundice',
 'white discharge from eye',
 'irritable infant',
 'abusing alcohol',
 'fainting',
 'hostile behavior',
 'drug abuse',
 'sharp abdominal pain',
 'feeling ill',
 'vomiting',
 'headache',
 'nausea',
 'diarrhea',
 'vaginal itching',
 'painful urination',
 'involuntary urination',
 'pain during intercourse',
 'frequent urination',
 'lower abdominal pain',
 'vaginal discharge',
 'blood in urine',
 'hot flashes',
 'intermenstrual bleeding',
 'hand or finger pain',
 'wrist pain',
 'hand or finger swelling',
 'arm pain',
 'wrist swelling',
 'arm stiffness or tightness',
 'arm swelling',
 'hand or finger stiffness or tightness',
 'lip swelling',
 'toothache',
 'abnormal appearing skin',
 'skin lesion',
 'acne or pimples',
 'facial pain',
 'mouth ulcer',
 'skin growth',
 'diminished vision',
 'double vision',
 'symptoms of eye',
 'pain in eye',
 'abnormal movement of eyelid',
 'foreign body sensation in eye',
 'irregular appearing scalp',
 'back pain',
 'neck pain',
 'low back pain',
 'pain of the anus',
 'pain during pregnancy',
 'pelvic pain',
 'impotence',
 'vomiting blood',
 'regurgitation',
 'burning abdominal pain',
 'restlessness',
 'wheezing',
 'peripheral edema',
 'neck mass',
 'ear pain',
 'jaw swelling',
 'mouth dryness',
 'neck swelling',
 'knee pain',
 'foot or toe pain',
 'ankle pain',
 'bones are painful',
 'elbow pain',
 'knee swelling',
 'skin moles',
 'weight gain',
 'problems with movement',
 'knee stiffness or tightness',
 'leg swelling',
 'foot or toe swelling',
 'heartburn',
 'infant feeding problem',
 'vaginal pain',
 'vaginal redness',
 'weakness',
 'decreased heart rate',
 'increased heart rate',
 'ringing in ear',
 'plugged feeling in ear',
 'itchy ear(s)',
 'frontal headache',
 'fluid in ear',
 'spots or clouds in vision',
 'eye redness',
 'lacrimation',
 'itchiness of eye',
 'blindness',
 'eye burns or stings',
 'decreased appetite',
 'excessive anger',
 'loss of sensation',
 'focal weakness',
 'symptoms of the face',
 'disturbance of memory',
 'paresthesia',
 'side pain',
 'fever',
 'shoulder pain',
 'shoulder stiffness or tightness',
 'ache all over',
 'lower body pain',
 'problems during pregnancy',
 'spotting or bleeding during pregnancy',
 'cramps and spasms',
 'upper abdominal pain',
 'stomach bloating',
 'changes in stool appearance',
 'unusual color or odor to urine',
 'kidney mass',
 'symptoms of prostate',
 'difficulty breathing',
 'rib pain',
 'joint pain',
 'hand or finger lump or mass',
 'chills',
 'groin pain',
 'fatigue',
 'regurgitation.1',
 'symptoms of the kidneys',
 'melena',
 'coughing up sputum',
 'seizures',
 'delusions or hallucinations',
 'excessive urination at night',
 'bleeding from eye',
 'rectal bleeding',
 'constipation',
 'temper problems',
 'coryza',
 'hemoptysis',
 'allergic reaction',
 'congestion in chest',
 'sleepiness',
 'apnea',
 'abnormal breathing sounds',
 'blood clots during menstrual periods',
 'pulling at ears',
 'gum pain',
 'redness in ear',
 'fluid retention',
 'flu-like syndrome',
 'sinus congestion',
 'painful sinuses',
 'fears and phobias',
 'recent pregnancy',
 'uterine contractions',
 'burning chest pain',
 'back cramps or spasms',
 'back mass or lump',
 'nosebleed',
 'long menstrual periods',
 'heavy menstrual flow',
 'unpredictable menstruation',
 'painful menstruation',
 'infertility',
 'frequent menstruation',
 'sweating',
 'mass on eyelid',
 'swollen eye',
 'eyelid swelling',
 'eyelid lesion or rash',
 'symptoms of bladder',
 'irregular appearing nails',
 'itching of skin',
 'hurts to breath',
 'skin dryness, peeling, scaliness, or roughness',
 'skin irritation',
 'itchy scalp',
 'warts',
 'skin rash',
 'mass or swelling around the anus',
 'ankle swelling',
 'elbow swelling',
 'bleeding from ear',
 'hand or finger weakness',
 'low self-esteem',
 'itching of the anus',
 'swollen or red tonsils',
 'hip stiffness or tightness',
 'mouth pain',
 'arm weakness',
 'obsessions and compulsions',
 'antisocial behavior',
 'sneezing',
 'leg weakness',
 'hysterical behavior',
 'arm lump or mass',
 'bleeding gums',
 'pain in gums',
 'diaper rash',
 'hesitancy',
 'back stiffness or tightness',
 'low urine output']

In [47]:
description_df.columns.tolist()

['Disease', 'Description']

In [48]:
medications_df.columns.tolist()

['Disease', 'Medication']

In [49]:
precautions_df.columns.tolist()

['Disease', 'Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']

In [50]:
diet_df.columns.tolist()

['Disease', 'Diet']

In [51]:
workout_df.columns.tolist()

['Disease', 'Workouts']

In [52]:
print(disease_df["diseases"].nunique())

print(description_df["Disease"].nunique())

print(medications_df["Disease"].nunique())

print(precautions_df["Disease"].nunique())

print(diet_df["Disease"].nunique())

print(workout_df["Disease"].nunique())

100
100
100
100
100
100

In [53]:
set(disease_df["diseases"]) - set(description_df["Disease"])

{'actinic keratosis',
 'acute bronchiolitis',
 'acute bronchitis',
 'acute bronchospasm',
 'acute kidney injury',
 'acute pancreatitis',
 'acute sinusitis',
 'allergy',
 'angina',
 'anxiety',
 'appendicitis',
 'arthritis of the hip',
 'asthma',
 'benign prostatic hyperplasia (bph)',
 'brachial neuritis',
 'bursitis',
 'carpal tunnel syndrome',
 'cholecystitis',
 'chronic back pain',
 'chronic constipation',
 'chronic obstructive pulmonary disease (copd)',
 'common cold',
 'complex regional pain syndrome',
 'concussion',
 'conjunctivitis',
 'conjunctivitis due to allergy',
 'contact dermatitis',
 'cornea infection',
 'croup',
 'cystitis',
 'degenerative disc disease',
 'dental caries',
 'depression',
 'developmental disability',
 'diaper rash',
 'diverticulitis',
 'drug reaction',
 'ear drum damage',
 'eczema',
 'esophagitis',
 'eustachian tube dysfunction (ear disorder)',
 'fungal infection of the hair',
 'gallstone',
 'gastrointestinal hemorrhage',
 'gout',
 'gum disease',
 'heart attack',
 'heart failure',
 'hemorrhoids',
 'herniated disk',
 'hiatal hernia',
 'hyperemesis gravidarum',
 'hypertensive heart disease',
 'hypoglycemia',
 'idiopathic excessive menstruation',
 'idiopathic irregular menstrual cycle',
 'idiopathic painful menstruation',
 'infectious gastroenteritis',
 'injury to the arm',
 'injury to the leg',
 'injury to the trunk',
 'liver disease',
 'macular degeneration',
 'marijuana abuse',
 'multiple sclerosis',
 'noninfectious gastroenteritis',
 'nose disorder',
 'obstructive sleep apnea (osa)',
 "otitis externa (swimmer's ear)",
 'otitis media',
 'pain after an operation',
 'panic disorder',
 'pelvic inflammatory disease',
 'peripheral nerve disorder',
 'personality disorder',
 'pneumonia',
 'problem during pregnancy',
 'psoriasis',
 'pyogenic skin infection',
 'rectal disorder',
 'schizophrenia',
 'seasonal allergies (hay fever)',
 'sebaceous cyst',
 'sepsis',
 'sickle cell crisis',
 'sinus bradycardia',
 'skin pigmentation disorder',
 'skin polyp',
 'spinal stenosis',
 'spondylosis',
 'spontaneous abortion',
 'sprain or strain',
 'strep throat',
 'stye',
 'temporary or benign blood in urine',
 'threatened pregnancy',
 'urinary tract infection',
 'vaginal cyst',
 'vaginitis',
 'vulvodynia'}

In [54]:
set(description_df["Disease"]) - set(disease_df["diseases"])

{'Actinic keratosis',
 'Acute bronchiolitis',
 'Acute bronchitis',
 'Acute bronchospasm',
 'Acute kidney injury',
 'Acute pancreatitis',
 'Acute sinusitis',
 'Allergy',
 'Angina',
 'Anxiety',
 'Appendicitis',
 'Arthritis of the hip',
 'Asthma',
 'Benign prostatic hyperplasia (BPH)',
 'Brachial neuritis',
 'Bursitis',
 'Carpal tunnel syndrome',
 'Cholecystitis',
 'Chronic back pain',
 'Chronic constipation',
 'Chronic obstructive pulmonary disease (COPD)',
 'Common cold',
 'Complex regional pain syndrome',
 'Concussion',
 'Conjunctivitis',
 'Conjunctivitis due to allergy',
 'Contact dermatitis',
 'Cornea infection',
 'Croup',
 'Cystitis',
 'Degenerative disc disease',
 'Dental caries',
 'Depression',
 'Developmental disability',
 'Diaper rash',
 'Diverticulitis',
 'Drug reaction',
 'Ear drum damage',
 'Eczema',
 'Esophagitis',
 'Eustachian tube dysfunction (ear disorder)',
 'Fungal infection of the hair',
 'Gallstone',
 'Gastrointestinal hemorrhage',
 'Gout',
 'Gum disease',
 'Heart attack',
 'Heart failure',
 'Hemorrhoids',
 'Herniated disk',
 'Hiatal hernia',
 'Hyperemesis gravidarum',
 'Hypertensive heart disease',
 'Hypoglycemia',
 'Idiopathic excessive menstruation',
 'Idiopathic irregular menstrual cycle',
 'Idiopathic painful menstruation',
 'Infectious gastroenteritis',
 'Injury to the arm',
 'Injury to the leg',
 'Injury to the trunk',
 'Liver disease',
 'Macular degeneration',
 'Marijuana abuse',
 'Multiple sclerosis',
 'Noninfectious gastroenteritis',
 'Nose disorder',
 'Obstructive sleep apnea (OSA)',
 "Otitis externa (swimmer's ear)",
 'Otitis media',
 'Pain after an operation',
 'Panic disorder',
 'Pelvic inflammatory disease',
 'Peripheral nerve disorder',
 'Personality disorder',
 'Pneumonia',
 'Problem during pregnancy',
 'Psoriasis',
 'Pyogenic skin infection',
 'Rectal disorder',
 'Schizophrenia',
 'Seasonal allergies (hay fever)',
 'Sebaceous cyst',
 'Sepsis',
 'Sickle cell crisis',
 'Sinus bradycardia',
 'Skin pigmentation disorder',
 'Skin polyp',
 'Spinal stenosis',
 'Spondylosis',
 'Spontaneous abortion',
 'Sprain or strain',
 'Strep throat',
 'Stye',
 'Temporary or benign blood in urine',
 'Threatened pregnancy',
 'Urinary tract infection',
 'Vaginal cyst',
 'Vaginitis',
 'Vulvodynia'}

In [ ]:
# Dataset 1 - SympScan Analysis

## Objective
Analyze the SympScan dataset and understand its structure before preprocessing.

## Files Included
- Diseases_and_Symptoms_dataset.csv
- description.csv
- medications.csv
- precautions.csv
- diets.csv
- workout.csv

## Initial Observations
- Successfully loaded all files.
- No duplicate rows found.
- Disease prediction dataset uses binary symptom encoding (0 = symptom absent, 1 = symptom present).
- Remaining files provide supplementary information such as descriptions, medications, diets, precautions, and workouts.

In [56]:
disease_clean = disease_df.copy()

description_clean = description_df.copy()

medications_clean = medications_df.copy()

precautions_clean = precautions_df.copy()

diet_clean = diet_df.copy()

workout_clean = workout_df.copy()

In [57]:
description_clean["Disease"].head(10)

0                Panic disorder
1                     Vaginitis
2      Problem during pregnancy
3            Acute pancreatitis
4                        Asthma
5    Infectious gastroenteritis
6               Acute sinusitis
7              Cornea infection
8               Marijuana abuse
9                      Bursitis
Name: Disease, dtype: object

In [58]:
medications_clean["Disease"].head(10)

precautions_clean["Disease"].head(10)

diet_clean["Disease"].head(10)

workout_clean["Disease"].head(10)

0                Panic disorder
1                     Vaginitis
2      Problem during pregnancy
3            Acute pancreatitis
4                        Asthma
5    Infectious gastroenteritis
6               Acute sinusitis
7              Cornea infection
8               Marijuana abuse
9                      Bursitis
Name: Disease, dtype: object

In [60]:
description_clean["Disease"] = description_clean["Disease"].str.strip()

medications_clean["Disease"] = medications_clean["Disease"].str.strip()

precautions_clean["Disease"] = precautions_clean["Disease"].str.strip()

diet_clean["Disease"] = diet_clean["Disease"].str.strip()

workout_clean["Disease"] = workout_clean["Disease"].str.strip()

In [61]:
description_clean["Disease"].duplicated().sum()

medications_clean["Disease"].duplicated().sum()

precautions_clean["Disease"].duplicated().sum()

diet_clean["Disease"].duplicated().sum()

workout_clean["Disease"].duplicated().sum()

np.int64(0)

In [62]:
description_clean["Disease"] = description_clean["Disease"].str.title()

medications_clean["Disease"] = medications_clean["Disease"].str.title()

precautions_clean["Disease"] = precautions_clean["Disease"].str.title()

diet_clean["Disease"] = diet_clean["Disease"].str.title()

workout_clean["Disease"] = workout_clean["Disease"].str.title()

In [63]:
description_clean.head()

medications_clean.head()

precautions_clean.head()

diet_clean.head()

workout_clean.head()

                    Disease                                           Workouts
0            Panic Disorder  ["Deep breathing exercises: Calm your mind by ...
1                 Vaginitis  ["Pelvic floor exercises: Strengthen pelvic mu...
2  Problem During Pregnancy  ["Prenatal yoga: Gentle stretches safe for pre...
3        Acute Pancreatitis  ["Avoid heavy lifting: Prevent strain on pancr...
4                    Asthma  ["Breathing exercises: Improve lung function",...

In [ ]:
# Data Cleaning - Dataset 1

## Cleaning Performed

- Created copies of all original datasets.
- Removed leading and trailing spaces from disease names.
- Standardized disease names for consistency.
- Verified duplicate disease entries in lookup tables.