In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
import os

os.chdir(r"C:\Users\admin\Desktop\MedAssist AI")

print(os.getcwd())

C:\Users\admin\Desktop\MedAssist AI

In [3]:
os.listdir("datasets/Dataset_3_SymptomsToDisease")

['data.csv', 'final_symptoms_to_disease.csv']

In [4]:
dataset3_df = pd.read_csv("datasets/Dataset_3_SymptomsToDisease/final_symptoms_to_disease.csv")

In [5]:
dataset3_df.shape

(192715, 2)

In [6]:
dataset3_df.head()

         diseases                                       symptom_text
0  panic disorder  anxiety and nervousness, shortness of breath, ...
1  panic disorder  shortness of breath, depressive or psychotic s...
2  panic disorder  anxiety and nervousness, depression, shortness...
3  panic disorder  anxiety and nervousness, depressive or psychot...
4  panic disorder  anxiety and nervousness, depression, insomnia,...

In [7]:
dataset3_df.isnull()

        diseases  symptom_text
0          False         False
1          False         False
2          False         False
3          False         False
4          False         False
...          ...           ...
192710     False         False
192711     False         False
192712     False         False
192713     False         False
192714     False         False

[192715 rows x 2 columns]

In [8]:
dataset3_df.isnull().sum()

diseases        0
symptom_text    0
dtype: int64

In [10]:

dataset3_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192715 entries, 0 to 192714
Data columns (total 2 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   diseases      192715 non-null  object
 1   symptom_text  192715 non-null  object
dtypes: object(2)
memory usage: 2.9+ MB

In [12]:
dataset3_df.duplicated().sum()

np.int64(28988)

In [13]:
dataset3_df.describe(include="all")

        diseases                           symptom_text
count     192715                                 192715
unique       254                                 149241
top     cystitis  shortness of breath, sharp chest pain
freq        1219                                     18

In [15]:
dataset3_df["diseases"].nunique()

254