In [5]:
# Data Cleaning and Standardization

## Objective

This notebook cleans and standardizes all datasets used in the MedAssist AI project before merging and model training.

### Datasets

- Dataset 1: SympScan Knowledge Base
- Dataset 2: Final Augmented Disease Dataset
- Dataset 3: Symptoms-to-Disease Dataset

### Tasks

- Reload datasets
- Create working copies
- Standardize disease names
- Clean text data
- Investigate duplicate records
- Validate cleaned datasets
- Save cleaned datasets

SyntaxError: invalid syntax (4211436521.py, line 5)

In [6]:
import pandas as pd
import numpy as np
import os

In [7]:


os.chdir(r"C:\Users\admin\Desktop\MedAssist AI")

print(os.getcwd())

C:\Users\admin\Desktop\MedAssist AI

In [8]:
# Dataset 1
disease_df = pd.read_csv("datasets/Dataset_1_SympScan/Diseases_and_Symptoms_dataset.csv")
description_df = pd.read_csv("datasets/Dataset_1_SympScan/description.csv")
medications_df = pd.read_csv("datasets/Dataset_1_SympScan/medications.csv")
precautions_df = pd.read_csv("datasets/Dataset_1_SympScan/precautions.csv")
diet_df = pd.read_csv("datasets/Dataset_1_SympScan/diets.csv")
workout_df = pd.read_csv("datasets/Dataset_1_SympScan/workout.csv")

# Dataset 2
dataset2_df = pd.read_csv("datasets/Dataset_2_DiseasePrediction/Final_Augmented_dataset_Diseases_and_Symptoms.csv")

# Dataset 3
dataset3_df = pd.read_csv("datasets/Dataset_3_SymptomsToDisease/final_symptoms_to_disease.csv")

In [9]:
disease_clean = disease_df.copy()
description_clean = description_df.copy()
medications_clean = medications_df.copy()
precautions_clean = precautions_df.copy()
diet_clean = diet_df.copy()
workout_clean = workout_df.copy()

dataset2_clean = dataset2_df.copy()

dataset3_clean = dataset3_df.copy()

In [10]:
print("Dataset 1:", disease_clean.shape)
print("Dataset 2:", dataset2_clean.shape)
print("Dataset 3:", dataset3_clean.shape)

Dataset 1: (96088, 231)
Dataset 2: (246945, 378)
Dataset 3: (192715, 2)

In [11]:
print("Dataset 1:")
print(disease_clean.columns[0])

print("\nDescription:")
print(description_clean.columns[0])

print("\nMedication:")
print(medications_clean.columns[0])

print("\nPrecaution:")
print(precautions_clean.columns[0])

print("\nDiet:")
print(diet_clean.columns[0])

print("\nWorkout:")
print(workout_clean.columns[0])

print("\nDataset 2:")
print(dataset2_clean.columns[0])

print("\nDataset 3:")
print(dataset3_clean.columns[0])

Dataset 1:
diseases

Description:
Disease

Medication:
Disease

Precaution:
Disease

Diet:
Disease

Workout:
Disease

Dataset 2:
diseases

Dataset 3:
diseases

In [13]:
# Dataset 1
disease_clean.rename(columns={"diseases": "Disease"}, inplace=True)

# Dataset 2
dataset2_clean.rename(columns={"diseases": "Disease"}, inplace=True)

# Dataset 3
dataset3_clean.rename(columns={"diseases": "Disease"}, inplace=True)

In [14]:
print(disease_clean.columns[0])
print(dataset2_clean.columns[0])
print(dataset3_clean.columns[0])

Disease
Disease
Disease

In [ ]:
## Column Name Standardization

To maintain consistency across all datasets, the disease column was standardized to the name **Disease**. This simplifies merging and preprocessing in later stages.

In [15]:
# Dataset 1
disease_clean["Disease"] = disease_clean["Disease"].str.strip()
description_clean["Disease"] = description_clean["Disease"].str.strip()
medications_clean["Disease"] = medications_clean["Disease"].str.strip()
precautions_clean["Disease"] = precautions_clean["Disease"].str.strip()
diet_clean["Disease"] = diet_clean["Disease"].str.strip()
workout_clean["Disease"] = workout_clean["Disease"].str.strip()

# Dataset 2
dataset2_clean["Disease"] = dataset2_clean["Disease"].str.strip()

# Dataset 3
dataset3_clean["Disease"] = dataset3_clean["Disease"].str.strip()

In [16]:
# Dataset 1
disease_clean["Disease"] = disease_clean["Disease"].str.title()
description_clean["Disease"] = description_clean["Disease"].str.title()
medications_clean["Disease"] = medications_clean["Disease"].str.title()
precautions_clean["Disease"] = precautions_clean["Disease"].str.title()
diet_clean["Disease"] = diet_clean["Disease"].str.title()
workout_clean["Disease"] = workout_clean["Disease"].str.title()

# Dataset 2
dataset2_clean["Disease"] = dataset2_clean["Disease"].str.title()

# Dataset 3
dataset3_clean["Disease"] = dataset3_clean["Disease"].str.title()

In [17]:
print(disease_clean["Disease"].head())

print(dataset2_clean["Disease"].head())

print(dataset3_clean["Disease"].head())

0    Panic Disorder
1    Panic Disorder
2    Panic Disorder
3    Panic Disorder
4    Panic Disorder
Name: Disease, dtype: object
0    Panic Disorder
1    Panic Disorder
2    Panic Disorder
3    Panic Disorder
4    Panic Disorder
Name: Disease, dtype: object
0    Panic Disorder
1    Panic Disorder
2    Panic Disorder
3    Panic Disorder
4    Panic Disorder
Name: Disease, dtype: object

In [ ]:
## Disease Name Standardization

The disease names in all datasets were standardized by:
- Removing leading and trailing spaces.
- Converting names to title case.
- Ensuring consistency across datasets for future merging.

In [18]:
print("Total Rows:", len(dataset2_clean))

print("Duplicate Rows:", dataset2_clean.duplicated().sum())

print("Rows After Removing Duplicates:", len(dataset2_clean.drop_duplicates()))

Total Rows: 246945
Duplicate Rows: 57298
Rows After Removing Duplicates: 189647

In [19]:
dataset2_clean[dataset2_clean.duplicated()].head(10)

,Disease,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
147,Panic Disorder,1,0,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
181,Panic Disorder,1,1,1,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
247,Panic Disorder,1,1,1,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
281,Panic Disorder,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
283,Panic Disorder,0,1,1,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
312,Panic Disorder,1,1,1,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
316,Panic Disorder,0,1,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
333,Panic Disorder,1,1,0,1,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
334,Panic Disorder,1,1,1,1,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
341,Panic Disorder,0,1,0,1,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [20]:
print("Total Rows:", len(dataset3_clean))

print("Duplicate Rows:", dataset3_clean.duplicated().sum())

print("Rows After Removing Duplicates:", len(dataset3_clean.drop_duplicates()))

Total Rows: 192715
Duplicate Rows: 28988
Rows After Removing Duplicates: 163727

In [21]:
dataset3_clean[dataset3_clean.duplicated()].head(10)

            Disease                                       symptom_text
147  Panic Disorder  anxiety and nervousness, shortness of breath, ...
181  Panic Disorder  anxiety and nervousness, depression, shortness...
247  Panic Disorder  anxiety and nervousness, depression, shortness...
281  Panic Disorder  depressive or psychotic symptoms, insomnia, ir...
283  Panic Disorder  depression, shortness of breath, depressive or...
312  Panic Disorder  anxiety and nervousness, depression, shortness...
316  Panic Disorder  depression, depressive or psychotic symptoms, ...
333  Panic Disorder  anxiety and nervousness, depression, depressiv...
334  Panic Disorder  anxiety and nervousness, depression, shortness...
341  Panic Disorder  depression, depressive or psychotic symptoms, ...

In [ ]:
## Duplicate Record Investigation

Before removing duplicate records, the datasets were inspected to determine whether the duplicates were introduced intentionally (e.g., during data augmentation) or were accidental duplicates.

This investigation helps ensure that useful training data is not removed unnecessarily.

In [22]:
dataset3_clean = dataset3_clean.drop_duplicates().reset_index(drop=True)

In [23]:
print(dataset3_clean.duplicated().sum())

0

In [24]:
dataset3_clean.shape

(163727, 2)

In [25]:
dataset2_clean[dataset2_clean.duplicated()].head(10)

,Disease,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
147,Panic Disorder,1,0,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
181,Panic Disorder,1,1,1,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
247,Panic Disorder,1,1,1,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
281,Panic Disorder,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
283,Panic Disorder,0,1,1,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
312,Panic Disorder,1,1,1,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
316,Panic Disorder,0,1,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
333,Panic Disorder,1,1,0,1,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
334,Panic Disorder,1,1,1,1,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
341,Panic Disorder,0,1,0,1,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
## Duplicate Handling

### Dataset 1
- No duplicate records were found.

### Dataset 2
- Duplicate records were identified.
- The dataset is an augmented dataset, so duplicate rows were investigated before deciding whether to remove them.

### Dataset 3
- Exact duplicate records were removed because they did not contribute additional information.

In [26]:
dataset2_clean = dataset2_clean.drop_duplicates().reset_index(drop=True)

In [27]:
print(dataset2_clean.shape)

print(dataset2_clean.duplicated().sum())

(189647, 378)
0

In [28]:
print(dataset3_clean.shape)

print(dataset3_clean.duplicated().sum())

(163727, 2)
0

In [ ]:
## Duplicate Removal

### Dataset 2
- 57,298 duplicate records were identified.
- Exact duplicate rows were removed.
- Remaining records: 189,647.

### Dataset 3
- 28,988 duplicate records were identified.
- Exact duplicate rows were removed.
- Remaining records: 163,727.

Removing duplicate records helps reduce redundancy and prevents model bias during training.

In [30]:
dataset2_clean.shape
dataset2_clean.duplicated().sum()

dataset3_clean.shape
dataset3_clean.duplicated().sum()

np.int64(0)

In [31]:
description_clean["Description"] = (
    description_clean["Description"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [32]:
medications_clean["Medication"] = (
    medications_clean["Medication"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [33]:
diet_clean["Diet"] = (
    diet_clean["Diet"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [34]:
workout_clean["Workouts"] = (
    workout_clean["Workouts"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [35]:
dataset3_clean["symptom_text"] = (
    dataset3_clean["symptom_text"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [36]:
print(description_clean.head(2))
print(medications_clean.head(2))
print(diet_clean.head(2))
print(workout_clean.head(2))
print(dataset3_clean.head(2))

          Disease                                        Description
0  Panic Disorder  Panic disorder is a mental health condition ma...
1       Vaginitis  Vaginitis is inflammation of the vaginal tissu...
          Disease                                         Medication
0  Panic Disorder  ['SSRIs (e.g., Sertraline, Fluoxetine)', 'Benz...
1       Vaginitis  ['Metronidazole', 'Clindamycin', 'Fluconazole'...
          Disease                                               Diet
0  Panic Disorder  ['Magnesium-rich foods (spinach, pumpkin seeds...
1       Vaginitis  ['Probiotics (yogurt, kefir, sauerkraut)', 'Lo...
          Disease                                           Workouts
0  Panic Disorder  ["Deep breathing exercises: Calm your mind by ...
1       Vaginitis  ["Pelvic floor exercises: Strengthen pelvic mu...
          Disease                                       symptom_text
0  Panic Disorder  anxiety and nervousness, shortness of breath, ...
1  Panic Disorder  shortness of breath, depressive or psychotic s...

In [37]:
print("Dataset 1 Missing Values:", disease_clean.isnull().sum().sum())
print("Description Missing Values:", description_clean.isnull().sum().sum())
print("Medication Missing Values:", medications_clean.isnull().sum().sum())
print("Precaution Missing Values:", precautions_clean.isnull().sum().sum())
print("Diet Missing Values:", diet_clean.isnull().sum().sum())
print("Workout Missing Values:", workout_clean.isnull().sum().sum())

print("Dataset 2 Missing Values:", dataset2_clean.isnull().sum().sum())
print("Dataset 3 Missing Values:", dataset3_clean.isnull().sum().sum())

Dataset 1 Missing Values: 0
Description Missing Values: 0
Medication Missing Values: 0
Precaution Missing Values: 0
Diet Missing Values: 0
Workout Missing Values: 0
Dataset 2 Missing Values: 0
Dataset 3 Missing Values: 0

In [38]:
import os

os.makedirs("cleaned_datasets", exist_ok=True)

In [39]:
disease_clean.to_csv("cleaned_datasets/disease_clean.csv", index=False)
description_clean.to_csv("cleaned_datasets/description_clean.csv", index=False)
medications_clean.to_csv("cleaned_datasets/medications_clean.csv", index=False)
precautions_clean.to_csv("cleaned_datasets/precautions_clean.csv", index=False)
diet_clean.to_csv("cleaned_datasets/diet_clean.csv", index=False)
workout_clean.to_csv("cleaned_datasets/workout_clean.csv", index=False)

dataset2_clean.to_csv("cleaned_datasets/dataset2_clean.csv", index=False)
dataset3_clean.to_csv("cleaned_datasets/dataset3_clean.csv", index=False)

In [40]:
os.listdir("cleaned_datasets")

['dataset2_clean.csv',
 'dataset3_clean.csv',
 'description_clean.csv',
 'diet_clean.csv',
 'disease_clean.csv',
 'medications_clean.csv',
 'precautions_clean.csv',
 'workout_clean.csv']